export type DIALOGS_POPUP_ENABLE = "DIALOGS_POPUP_ENABLE";
export const DIALOGS_POPUP_ENABLE: DIALOGS_POPUP_ENABLE = "DIALOGS_POPUP_ENABLE";
export type DIALOGS_POPUP_DISABLE = "DIALOGS_POPUP_DISABLE";
export const DIALOGS_POPUP_DISABLE: DIALOGS_POPUP_DISABLE = "DIALOGS_POPUP_DISABLE";
export type DIALOGS_POPUP_CLEAR = "DIALOGS_POPUP_CLEAR";
export const DIALOGS_POPUP_CLEAR: DIALOGS_POPUP_CLEAR = "DIALOGS_POPUP_CLEAR";
export type DIALOGS_MODAL_ENABLE = "DIALOGS_MODAL_ENABLE";
export const DIALOGS_MODAL_ENABLE: DIALOGS_MODAL_ENABLE = "DIALOGS_MODAL_ENABLE";
export type DIALOGS_MODAL_DISABLE = "DIALOGS_MODAL_DISABLE";
export const DIALOGS_MODAL_DISABLE: DIALOGS_MODAL_DISABLE = "DIALOGS_MODAL_DISABLE";
export type DIALOGS_MODAL_CLEAR = "DIALOGS_MODAL_CLEAR";
export const DIALOGS_MODAL_CLEAR: DIALOGS_MODAL_CLEAR = "DIALOGS_MODAL_CLEAR";

export interface IDialogsPopupAction {
    type: DIALOGS_POPUP_ENABLE | DIALOGS_POPUP_DISABLE | DIALOGS_POPUP_CLEAR;
    elementID: string;
}

export interface IDialogsModalAction {
    type: DIALOGS_MODAL_ENABLE | DIALOGS_MODAL_DISABLE | DIALOGS_MODAL_CLEAR;
    elementID: string;
}

export interface IOtherAction {
    type: "";
}

export const otherAction: IOtherAction = { "type": "" };
